easclepius/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('hospital/',include('hospital.urls')),
    #path('hospitalsearch/',include('hospitalsearch.urls')),
    path('admin/', admin.site.urls),
]

hospital/urls.py
from django.views.generic.base import TemplateView, RedirectView
from . import models, views
from django.urls import path,include
from django.conf.urls import url
app_name = 'hospital'

urlpatterns = [
    path("",RedirectView.as_view(url="authentica"),name="auth_manager"),
    path("authentica", views.authentication_manager,name="auth_manager"),
    path("home", views.home_view,name="home"),
    path("logout",views.logout_view,name='logout'),
    path("hospital", views.hospital_auth,name="hospital_login"),
    path("scan", TemplateView.as_view(template_name="scan.html"),name = "scan_manager"),
    path("views/<str:username>", views.profile_view,name="profile_view"),
    path("filter_hosp", views.filter_hospital,name="filter hospital"),
    path("_search",views.search_hosp,name="search_hosp"),
    path("_search/<str:license>", views.hosp_profile, name="hosp_profile"),
    path('find', views.search_hosp, name='find'),
    path('home/page', views.loadspec, name='page'),
    path('home/ans', views.specialfunc, name='ans'),
]

hospital/models.py
from django.db import models
from django.contrib.auth.models import User
from itertools import product
# Create your models here.

class Patient(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    phno = models.CharField(max_length=10)
    def __str__(self):
        return str(self.user)


class Hospital(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    license = models.CharField(unique = True, max_length=10)
    phno = models.CharField(max_length=10)
    location = models.CharField(max_length=100)
    description = models.CharField(max_length=100)
    intensity = models.FloatField(default=0)
    def __str__(self):
        return str(self.user)

class PatientDetails(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)

    SEX_CHOICES = (
        ('M','MALE'),
        ('F','FEMALE'),
        ('O','OTHER')
    )
    sex=models.CharField(max_length=7,choices = SEX_CHOICES,null=True, blank=True)
    date_of_birth = models.DateField(blank=True,null=True)

    BLOOD_GROUP_CHOICES = (
        ("A+","A+"),("B+","B+"),("AB+","AB+"), ("O+","O+"),
        ("A-","A-"),("B-","B-"),("AB-","AB-"),("O-","O-")
    )
    blood_group = models.CharField(max_length=10, choices = BLOOD_GROUP_CHOICES, null=True, blank=True)
    address = models.CharField(max_length=500, null=True, blank=True)
    pin_code = models.IntegerField(blank=True, null=True)
    district= models.CharField(max_length=100, null=True, blank=True)
    state = models.CharField(max_length=100, null=True, blank=True)
    taluka = models.CharField(max_length=100, null=True, blank=True)


    def get_score(self):
        score = 0
        variables = [self.sex, self.date_of_birth, self.blood_group, self.address, self.pin_code,
        self.district, self.state, self.taluka]
        for var in variables:
            if var != None:
                score+=1

        #calculates Returns the completion score
        return str(score)+"/"+str(len(variables))

    def __str__(self):
        return str(self.patient)

class HospitalDetails(models.Model):
    hospital = models.ForeignKey(Hospital, on_delete=models.CASCADE)
    RATING_CHOICE = (
    ('1',"POOR"),
    ('2','BELOW AVERAGE'),
    ('3','AVERAGE'),
    ('4','ABOVE AVERAGE'),
    ('5','AMAZING')
    )
    ratings = models.CharField(max_length=20, choices = RATING_CHOICE, default = '1')
    total_ratings = models.PositiveIntegerField(default = 0)
    speech_ratings = models.CharField(max_length=20, choices = RATING_CHOICE, default = '1')
    address = models.CharField(max_length=500, null=True, blank=True)
    pin_code = models.IntegerField(blank=True, null=True)
    district= models.CharField(max_length=100, null=True, blank=True)
    state = models.CharField(max_length=100, null=True, blank=True)
    taluka = models.CharField(max_length=100, null=True, blank=True)
    staff_strength = models.PositiveIntegerField(default=0)
    COST_CLASS = (
    ('1','CHEAP <200'),
    ('2','MODERATE <1000'),
    ('3','EXPENSIVE <10000'),
    ('4','FULL STAR > 10000')
    )
    cost_range = models.CharField(max_length=100, choices = COST_CLASS, default='4')
    operation_facilty = models.BooleanField(default=False)
    emergency_facility = models.BooleanField(default=False)
    beds_count = models.PositiveIntegerField(default = 10)
    beds_occupied = models.PositiveIntegerField(default = 10)

    def get_score(self):
        score = 0
        variables = [
            self.ratings,
            self.total_ratings,
            self.speech_ratings,
            self.address,
            self.pin_code,
            self.district,
            self.state,
            self.taluka,
            self.staff_strength,
            self.cost_range,
            self.operation_facilty,
            self.emergency_facility,
            self.beds_count,
            self.beds_occupied
        ]
        for var in variables:
            if var != None:
                score+=1

            #calculates Returns the completion score
        return str(score)+"/"+str(len(variables))
    def __str__(self):
        return str(self.hospital)


class Reviews(models.Model):
    hospital = models.ForeignKey(Hospital, on_delete=models.CASCADE)
    patient = models.ForeignKey(Patient, on_delete=models.PROTECT)
    spam = models.BooleanField(default=False)
    review = models.TextField(max_length=5000, null=True, blank=True)
    date_time = models.DateTimeField(auto_now=True)
    polarity = models.BooleanField(default=False)
    intensity = models.FloatField(default=0)
    def __str__(self):
        return str(self.hospital)+" <- "+str(self.patient)

class Disease(models.Model):
    hospital=models.ForeignKey(Hospital,on_delete=models.CASCADE)
    diseasetype=models.CharField(max_length=5000, default='nothing')
    data=models.TextField(max_length=10000,null=True,blank=True)
    def __str__(self):
        return str(self.user)

class MedicalHistory(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    hospital=models.ForeignKey(Hospital,on_delete=models.PROTECT)
    disease=models.ForeignKey(Disease,on_delete=models.CASCADE)
    comment = models.TextField(max_length=5000, null=True, blank=True)
    date_time=models.DateTimeField(auto_now=True)
    def __str__(self):
        return str(self.hospital)+" <- "+str(self.patient)

class special(models.Model):
    hospital=models.ForeignKey(Hospital,on_delete=models.CASCADE)
    diseasetype=models.CharField(max_length=5000, default='nothing')
    def gethosp(self):
        return self.hospital
    def __str__(self):
        return str(self.diseasetype)

class polarity(models.Model):
    hospital=models.ForeignKey(Hospital,on_delete=models.CASCADE)
    pol = models.FloatField(blank=True, null=True)

hospital/views.py
from django.shortcuts import render, redirect
from django.http import  HttpResponse
from django.contrib.auth import login,authenticate,logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_control
from django.contrib.auth.models import User
from . import models
from .helpers import auth_helpers
from .helpers import machine
from .helpers import analysis
from .helpers import sentiment
from .helpers import collocations as col
from django.utils import timezone
import nltk
import math
import os
import numpy as np
from nltk.stem import WordNetLemmatizer
from sklearn.linear_model import LogisticRegression
from bs4 import BeautifulSoup
from sklearn.externals import joblib
import nltk
from nltk.collocations import *
from nltk.corpus import stopwords
from nltk.corpus import webtext
from nltk.corpus import PlaintextCorpusReader
import numpy as np
from nltk import FreqDist
from hospital.models import Hospital
from django.db.models import Q
import operator

@cache_control(no_cache=True,must_revalidate=True,no_store=True)
@login_required(login_url="/hospital")
def home_view(request):
    form = auth_helpers.update_profile_entity(request)
    if auth_helpers.is_hospital(request.user):
        
        hosp = models.HospitalDetails.objects.get(hospital=models.Hospital.objects.get(user=request.user))
        review = models.Reviews.objects.filter(hospital=models.Hospital.objects.get(user=request.user))
        dis=models.special.objects.filter(hospital=models.Hospital.objects.get(user=request.user))
        print(request.user)
        #print("Database")
        #for asd in dis:
        #    print (asd.diseasetype)
        #print("/Database")
        #print (review)
        #print("BEHOLD")
        hospname=str(hosp.hospital)
        #print (hospname+"hello")
        live=[]
        file = open("/home/helios/Desktop/easclepius/easclepius/"+hospname,'a')
        #print (hosp.id)
        for i in review:
            live.append(i.review)
            print (i.review)
            file.write(str(i.review)+"\n")
        file.close()
        #print(col.give(hospname))
        good=col.give(hospname)
        good2=[]
        for y in good:
            good2.append(" ".join(str(x) for x in y))
        print("latest")
        print(live)
        #print (review.first())
        ###############################################machine.lie(live)
        ###############################################sent=machine.show_review()
        sent2=analysis.live_review(live)
        print("sent2=")
        print(sent2)
        hospi=models.Hospital.objects.get(user=request.user)
        #po=models.polarity.objects.filter(hospital=models.Hospital.objects.get(user=request.user))
        models.polarity.objects.filter(hospital=models.Hospital.objects.get(user=request.user)).delete()
        models.polarity.objects.create(hospital=hospi,pol = sent2[0])
        if(sent2!=0):
            if sent2[0]>0:
                p="Positive"
            else:
                p="Negative"
            sent3=int(math.floor(sent2[0]*10))
            sent5=sent2[1]*100
            sent6=sent2[2]*100
            sent7 = sent2[3] * 100
            li=[]
            li2=[]
            sent22=sent2[0]
            
        if(sent2==0):
            p="no data available"
            sent3="no data available"
            sent5="no data available"
            sent6="no data available"
            sent7="no data available"
            sent22=sent2
        return render(request, "hospital_profile.html",{'form':form,'hosp':hosp,"review":review,"sent":sent3,"sent2":sent22,
                                                      "sent5":sent5,"sent6":sent6,"sent7":sent7,"polarity":p,"good2":good2})
    ur=models.PatientDetails.objects.get(patient=models.Patient.objects.get(user=request.user))
    return render(request, "patient_profile.html",{'form':form,"ur":ur})


def authentication_manager(request):
    if not request.user.is_anonymous:
        return redirect("/hospital/home")
    if request.method == "GET":
        return render(request, "index.html")
    if request.method == "POST":
        req =  request.POST
        username = req["uname"]
        password = req["psw"]
        if req["meta"] == "login":
            #login logic here

            if auth_helpers.login_user(username, password, request):
                return redirect("/hospital/home")
            else:
                return redirect("/hospital")
        elif req["meta"] == "signup":

            #check if similar user exists
            if auth_helpers.signup_patient(request.POST):
                if auth_helpers.login_user(username, password, request):
                    return redirect("/hospital/home")
            return redirect("/hospital")
        else:
            #standard error page
            pass
    return redirect("/hospital")




def logout_view(request):
    if not request.user.is_anonymous:
        logout(request)
    return redirect("/hospital")


def hospital_auth(request):
    if not request.user.is_anonymous:
        return redirect("/hospital/hospital")
    if request.method == "GET":
        return render(request, "hospital_index.html")
    if request.method == "POST":
        req =  request.POST
        username = req["uname"]
        password = req["psw"]
        if req["meta"] == "login":
            #login logic here

            if auth_helpers.login_user(username, password, request):
                return redirect("/hospital/home")
            else:
                return redirect("/hospital/hospital")
        elif req["meta"] == "signup":

            #check if similar user exists
            if auth_helpers.signup_hospital(request.POST):
                if auth_helpers.login_user(username, password, request):
                    return redirect("/hospital/home")
            return redirect("/hospital/hospital")
        else:
            #standard error page
            pass
    return redirect("/hospital/hospital")

def profile_view(request,username):
    user = User.objects.get(username=username)
    #history = models.Disease.objects.filter(
        #models.MedicalHistory.objects.get(patient=models.Patient.objects.get(user=user)))
    patient = models.Patient.objects.get(user=user)
    hospital = models.Hospital.objects.get(user=request.user)
    if request.method == "POST":
        diseasetype = request.POST["diseasetype"]
        comment = request.POST["comment"]
        medicaldata = request.POST["medicaldata"]
        dis=models.Disease.objects.create(diseasetype=diseasetype,)
        data = models.MedicalHistory.objects.create(patient=patient, hospital=hospital)
        data.comment = comment
        data.disease.diseasetype = diseasetype
        data.disease.data = medicaldata
        data.date_time = timezone.now()
        data.save()
    return render(request, "profile_view.html", {"user": user})


def filter_hospital(request):
    if request.method == "GET":
        pass
    else:
        pass
    return render(request, 'filter.html')
        # pin_filter = None
        # cost_filter = None
        # name_filter = None
        # speciality_filter = None
        # star_filter = None
        # staff_strength_filter = None
def search_hosp(request):
    #try:
        flag=0
        if request.method=='POST':
            srch=request.POST['srh']
            if srch:
                print("true")
                match=Hospital.objects.filter(Q(user__username__icontains=srch)) 
                print(match)
                if match:
                    print ("pass")
                    m=[]
                    m.append(match)                                              #match 2d array(list inside a list)
                    ur=m
                    print(match)
                    return render(request,"allhospital.html",{"ur":ur,"flag":flag})
                match=models.special.objects.filter(Q(diseasetype__icontains=srch))
                #print(match[1].hospital_id)
                if match:
                    flag=1
                    print("passSpeciality")
                    m=[]
                    for k in match:
                        m.append(Hospital.objects.filter(Q(id__icontains=k.hospital_id)))
                    arr=[]
                    review=[]
                    print(m[1][0])
                   
                    for v in m:
                        review.append( models.Reviews.objects.filter(hospital_id=v[0].id)) #review 2d array
                        print(v[0].id)
                    overall={}
                    for re in review:#each hospital in re
                        summ=0
                        l=0
                        for r in re: #each review
                            summ=summ+r.intensity
                            idk=r
                            print(idk.hospital_id)
                            l=l+1
                        summ=summ/l
                        overall[Hospital.objects.get(id=idk.hospital_id)]=summ
                    asc = sorted(overall.items(), key=operator.itemgetter(1),reverse=True)
                    print(overall)
                    print(asc)
                    ur=m
                    todisp=[]
                    for ii in asc:				#stores only the key (ie Hospital object in array todisp)
                        todisp.append(ii[0])
                    return render(request,"allhospital.html",{"todisp":todisp,"flag":flag})
        

        return render(request,"allhospital.html",{"ur":ur})

    #except:
    #   return redirect("/hospital")
def hosp_profile(request,license):
    #one hospital cannot review another hospital
    print("IS RUNNING")
    try:
        hospital = models.Hospital.objects.get(license=license)
        hospitaldetails=models.HospitalDetails.objects.get(hospital=hospital)
    except (models.Hospital.DoesNotExist, models.HospitalDetails.DoesNotExist) :
        return  redirect("/hospital")

hospital/templates/dummy.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js"></script>
    <script type="text/javascript" src="/static/hospital_js/jquery.qrcode.js"></script>
    <script type="text/javascript" src="/static/hospital_js/qrcode.js"></script>
</head>
<body>
    This is a dummy html page user can see only when he is logged in.
    <br>
    Perhaps you can <a href="/hospital/logout">Logout</a> and try again to access this <a href="/hospital/home/">Page</a>.
    <div style="color:red">
        {{request.user.is_hospital}}
    </div>

    	<div id="qrcodeCanvas"></div>

        <script>
        var arr =  window.location.href.split("/");
        jQuery('#qrcodeCanvas').qrcode({

            text: arr[0]+"//"+arr[2]+"/"+arr[3]+"/views/"+"{{request.user}}"
            });
        </script>
</body>
</html>

hospital/templates/patient_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
     <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Patient Profile</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js"></script>
    <script type="text/javascript" src="/static/hospital_js/jquery.qrcode.js"></script>
    <script type="text/javascript" src="/static/hospital_js/qrcode.js"></script>

    <meta name="mobile-web-app-capable" content="yes">
    <link rel="icon" sizes="192x192" href="images/android-desktop.png">

    <!-- Add to homescreen for Safari on iOS -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="black">
    <meta name="apple-mobile-web-app-title" content="Material Design Lite">
    <link rel="apple-touch-icon-precomposed" href="images/ios-desktop.png">

    <!-- Tile icon for Win8 (144x144 + tile color) -->
    <meta name="msapplication-TileImage" content="images/touch/ms-touch-icon-144x144-precomposed.png">
    <meta name="msapplication-TileColor" content="#3372DF">
    <meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://www.w3schools.com/lib/w3-theme-blue-grey.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:regular,bold,italic,thin,light,bolditalic,black,medium&amp;lang=en">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://code.getmdl.io/1.3.0/material.cyan-light_blue.min.css">
    <link rel="stylesheet" href="/static/hospital_css/profile_styles.css">
    <link rel="stylesheet" href="/static/hospital_css/styles.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <!-- <script
      src="https://code.jquery.com/jquery-3.3.1.min.js"
      integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
      crossorigin="anonymous"></script> -->
<script defer src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script>
        $(function(){
            $("#id_pin_code").on('input propertychange paste',function(){
                    var content = $("#id_pin_code").val();
                    if(content.length === 6){
                        var xhttp = new XMLHttpRequest();
                        xhttp.open("GET", "http://postalpincode.in/api/pincode/"+content, false);

                        xhttp.send();
                        var response = JSON.parse(xhttp.responseText);
                        $("#id_district").val(response.PostOffice[0].District);
                        $("#id_state").val(response.PostOffice[0].State);
                        $("#id_taluka").val(response.PostOffice[0].Taluk);
                    }
            });
        });

    </script>

</head>
<body>
    <div style="color:red">
        {{request.user.is_hospital}}
    </div>
    <div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
      <header class="mdl-layout__header">
        <div class="mdl-layout__header-row">
          <!-- Title -->
          <span class="mdl-layout-title">E-asclepius</span>
             &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
            &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
             &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
             <a href="/hospital/_search" > see all hospitals</a>
             &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
            <h3><a href="/hospital/logout">Logout</a></h3>

        </div>

<form method="post" action="find">
		{% csrf_token %} 
<div class="form-group">
<input type="text" name="srh" class="form-control" width=1>
<button type="submit" class ="btn btn-danger">Search</button>
</div>
</form>


        <!-- Tabs -->
        <div class="mdl-layout__tab-bar mdl-js-ripple-effect">
          <a href="#scroll-tab-1" class="mdl-layout__tab is-active">Profile</a>
          <a href="#scroll-tab-2" class="mdl-layout__tab">Update Details</a>
          <a href="#scroll-tab-3" class="mdl-layout__tab">Scan QR</a>
          <a href="#scroll-tab-4" class="mdl-layout__tab">Medical History</a>
        </div>
      </header>
      <div class="mdl-layout__drawer">
        <span class="mdl-layout-title">E-asclepius</span>
      </div>
      <main class="mdl-layout__content">
        <section class="mdl-layout__tab-panel is-active" id="scroll-tab-1">
          <div class="page-content">
              <div class="w3-container w3-content">

 <div class="w3-panel w3-white w3-card w3-display-container">
     <p class="w3-text-blue"> User Name :
         <span class="w3-text-black">{{ur.patient.user.username}}</span>
     </p>
      <p class="w3-text-blue"> First Name:
         <span class="w3-text-black">{{ur.patient.user.first_name}}</span>
     </p>
      <p class="w3-text-blue"> Last Name:
         <span class="w3-text-black">{{ur.patient.user.last_name}}</span>
     </p>
     <p class="w3-text-blue"> Email Address:
         <span class="w3-text-black">{{ur.patient.user.email}}</span>
     </p>
      <p class="w3-text-blue"> Phone No:
         <span class="w3-text-black">{{ur.patient.phno}}</span>
     </p>
      <p class="w3-text-blue"> Gender:
         <span class="w3-text-black">{{ur.sex}}</span>
     </p>
      <p class="w3-text-blue"> Date Of Birth:
         <span class="w3-text-black">{{ur.date_of_birth}}</span>
     </p>
      <p class="w3-text-blue">Blood Group:
         <span class="w3-text-black">{{ur.blood_group}}</span>
     </p>
      <p class="w3-text-blue"> Address:
         <span class="w3-text-black">{{ur.address}}</span>
     </p>
      <p class="w3-text-blue">Pin Code:
         <span class="w3-text-black">{{ur.pin_code}}</span>
     </p>
      <p class="w3-text-blue">District:
         <span class="w3-text-black">{{ur.district}}</span>
     </p>
       <p class="w3-text-blue">State:
         <span class="w3-text-black">{{ur.state}}</span>
     </p>
       <p class="w3-text-blue">Taluka:
         <span class="w3-text-black">{{ur.taluka}}</span>
     </p>




 </div>
</div>

          </div>
        </section>
        <section class="mdl-layout__tab-panel" id="scroll-tab-2">
          <div class="page-content"><!-- Your content goes here -->
              <div class = "mdl-layout mdl-js-layout mdl-layout--fixed-header">

                  <form method="post" novalidate>
                {% csrf_token %}

                {% if form.non_field_errors %}
                  <ul>
                    {% for error in form.non_field_errors %}
                      <li>{{ error }}</li>
                    {% endfor %}
                  </ul>
                {% endif %}

                {% for hidden_field in form.hidden_fields %}
                  {% if hidden_field.errors %}
                    <ul>
                      {% for error in hidden_field.errors %}
                        <li>(Hidden field {{ hidden_field.name }}) {{ error }}</li>
                      {% endfor %}
                    </ul>
                  {% endif %}
                  {{ hidden_field }}
                {% endfor %}
              <div class="container">
                  <div class="row">
                  <div class="col-sm-4"></div>
                  <div class="col-sm-4">
                      <table border="1">
                        {% for field in form.visible_fields %}
                        <div class="form-group">
                          <tr>
                            <th>{{ field.label_tag }}</th>
                            <td>
                              {% if field.errors %}
                                <ul>
                                  {% for error in field.errors %}
                                    <li>{{ error }}</li>
                                  {% endfor %}
                                </ul>
                              {% endif %}
                              {{ field }}
                              {% if field.help_text %}
                                <br />{{ field.help_text }}
                              {% endif %}
                            </td>
                          </tr>
                          </div>
                        {% endfor %}

                      <tr>
                          <td><button type="reset" class="btn btn-danger">Reset</button></td>
                          <td><button type="submit" class="btn btn-success">Update</button></td>

                      </tr>
              </table>
                  </div>
                  <div class="col-sm-4"></div>
              </div>
              </div>

              </form>
              </div>
          </div>
        </section>
        <section class="mdl-layout__tab-panel" id="scroll-tab-3">
          <div class="page-content"><!-- Your content goes here -->
            <div id="qrcodeCanvas"></div>
          </div>
        </section>
        <section class="mdl-layout__tab-panel" id="scroll-tab-4">
          <div class="page-content"><!-- Your content goes here -->
               {% for i in history %}
<div class="w3-container w3-content">

 <div class="w3-panel w3-white w3-card w3-display-container">
     <p class="w3-text-blue"> Hospital name :
         <span class="w3-text-black">{{i.hospital.user.username}}</span>
     </p>
      <p class="w3-text-blue"> Date and Time :
         <span class="w3-text-black">{{i.date_time}}</span>
     </p>
      <p class="w3-text-blue"> Disease Type :
         <span class="w3-text-black">{{i.disease.diseasetype}}</span>
     </p>
      <p class="w3-text-blue"> Doctor Comment :
         <span class="w3-text-black">{{i.disease.comment}}</span>
     </p>
       <p class="w3-text-blue"> Patient Medical Data :
         <span class="w3-text-black">{{i.record}}</span>
     </p>
 </div>
</div>
{% endfor %}
          </div>
        </section>
      </main>
    </div>
    	<!-- <div id="qrcodeCanvas"></div> -->




        <script src="https://code.getmdl.io/1.3.0/material.min.js"></script>
        <script>
            var arr =  window.location.href.split("/");
            jQuery('#qrcodeCanvas').qrcode({

                text: arr[0]+"//"+arr[2]+"/"+arr[3]+"/views/"+"{{request.user}}"
                });

        </script>
</body>
</html>